## App
#spring.application.name=designAccent
#server.port=8080
#
## Database - change only these when going to Contabo
##app.db.host=localhost
##app.db.port=5432
##app.db.name=da
##app.db.username=postgres
##app.db.password=root
#
#app.db.host=ep-quiet-union-apnkqcmk.c-7.us-east-1.aws.neon.tech
##ep-quiet-un....aws.neon.tech
#app.db.port=5432
#app.db.name=neondb
#app.db.username=neondb_owner
#app.db.password=Moh@med2003
#
#server.address=0.0.0.0
#
#
## Spring Datasource
#spring.datasource.url=postgresql://neondb_owner:npg_HRguv36jlrzC@ep-quiet-union-apnkqcmk.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
#spring.datasource.username=${app.db.username}
#spring.datasource.password=${app.db.password}
#spring.datasource.driver-class-name=org.postgresql.Driver
#
## JPA
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.open-in-view=false
#
## JWT
#app.jwt.secret=designaccent-secret-key-minimum-32-characters-long
#app.jwt.expiration=3153600000000
#
## Contabo Storage
#app.storage.endpoint=https://eu2.contabostorage.com
#app.storage.bucket=design-accent
#app.storage.access-key=your-access-key
#app.storage.secret-key=your-secret-key
#app.storage.enabled=false

# App
spring.application.name=designAccent
#server.port=8080
server.port=${PORT:8080}
server.address=0.0.0.0

# Spring Datasource
spring.datasource.url=jdbc:postgresql://ep-quiet-union-apnkqcmk.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_HRguv36jlrzC
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# JWT
app.jwt.secret=designaccent-secret-key-minimum-32-characters-long
app.jwt.expiration=3153600000000